id: PF41A3377
initial_creation_type: ocr
source_metadata:
  volumes:
    b1d332c4527742a191b7273dd6ea29a2:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
